---
name: "VGMdb"
guid: "44616595-5798-47ad-8658-3c09f3030505"
version: 4
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Adds support for VGMdb to music libraries. Can provide both images and metadata for artists and albums."
description: >
  Adds support for VGMdb to music libraries. Can provide both images and metadata for artists and albums.

category: "Music"
artifacts:
  - "Jellyfin.Plugin.Vgmdb.dll"
changelog: |-
  - 10.9 (#23) @crobibero
